poll_tut/poll_tut/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.Home, name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls', namespace='polls')),
]

poll_tut/polls/urls.py
from django.urls import path, include
from . import views

app_name = "polls"
urlpatterns = [
    path('list/', views.poll_list, name='list'),
    path('<int:poll_id>/', views.poll_detail, name='details'),
]

poll_tut/polls/models.py
from django.db import models

class Poll(models.Model):
    text = models.CharField(max_length=250)
    pub_date = models.DateField()

    def __str__(self):
        return self.text

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length = 144)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll_tut/poll_tut/views.py
from django.http import HttpResponse
from django.shortcuts import render

def Home(request):
    context = {}
    return render(request, 'home.html', context)

poll_tut/polls/views.py
from django.shortcuts import render
from .models import Poll, Choice
from django.shortcuts import get_object_or_404

def poll_list(request):
    polls = Poll.objects.all()
    context = { 'polls': polls }
    return render(request, 'polls/polls_list.html', context)

def poll_detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    context = { 'poll' : poll }
    return render(request, 'polls/polls_detail.html', context)

def vote(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = poll.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/polls_detail.html', {'poll': poll, 'error_message': "You didn't select a choice.",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

poll_tut/polls/templates/polls/polls_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ poll }}</h1>
 <br>

{% for choice in poll.choice_set.all %}

{{ choice.choice_text }}
    <br />

{% endfor %}

{% endblock %}

poll_tut/polls/templates/polls/polls_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container border-top">
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            {% for poll in polls %}
            <div class="content">
                <div class="list-group">
                    <a type="list-group-item" href="{% url 'polls:details' poll.id %}" class="list-group-item d-flex justify-content-between align-items-center">
                        {{poll}}
                        <span class="badge badge-primary badge-pill">14</span>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

poll_tut/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }
˓→}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

poll_tut/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block custom_css %} {% endblock %}
    {% block title %}  {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"
    >
</head>
<body>
    {% include 'components/nav.html' %}
    {% block content %} {% endblock %}
    
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

poll_tut/templates/components/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'polls:list' %}">Poll <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
</nav>

poll_tut/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %} <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endblock %}
{% block title %} <title>Home</title> {% endblock %}

{% block content %}
    <h1>Hello, This is my Home page</h1>
{% endblock %}